// Datos mock realistas para desarrollo y pruebas de Solicitud de Trabajo (ST)
import {
  WorkRequest,
  WorkRequestStatus,
  WorkRequestItemStatus,
  WorkRequestOrigin,
  WorkRequestAttachment,
  WorkRequestStatusHistory,
} from './workRequestTypes';

export const mockWorkRequests: WorkRequest[] = [
  {
    id: 'st-001',
    folio: 'ST-2026-001',
    aircraftId: 'acft-001',
    status: WorkRequestStatus.DRAFT,
    priority: 'alta',
    createdByUserId: 'user-001',
    assignedToOfficeUserId: null,
    createdAt: '2026-04-10T10:00:00Z',
    updatedAt: '2026-04-10T10:00:00Z',
    items: [
      {
        id: 'item-001',
        workRequestId: 'st-001',
        sourceKind: 'maintenance_plan',
        sourceId: 'task-001',
        ataCode: '05-10-00',
        referenceCode: 'MP-001',
        title: 'Inspección 100H',
        description: 'Realizar inspección de 100 horas según manual.',
        regulatoryBasis: 'RB-100H',
        requiresComponentTracking: false,
        executionType: 'maintenance_application',
        priority: 'alta',
        aircraftHoursAtRequest: 1200,
        aircraftCyclesAtRequest: 800,
        dateAtRequest: '2026-04-10',
        itemStatus: WorkRequestItemStatus.PENDING,
        createdAt: '2026-04-10T10:00:00Z',
        updatedAt: '2026-04-10T10:00:00Z',
      },
      {
        id: 'item-002',
        workRequestId: 'st-001',
        sourceKind: 'discrepancy',
        sourceId: 'disc-001',
        ataCode: '27-30-00',
        referenceCode: 'DISC-001',
        title: 'Discrepancia en sistema de frenos',
        description: 'Se detectó pérdida de presión en frenos principales.',
        regulatoryBasis: 'RB-DISC',
        requiresComponentTracking: false,
        executionType: 'discrepancy_action',
        priority: 'media',
        aircraftHoursAtRequest: 1200,
        aircraftCyclesAtRequest: 800,
        dateAtRequest: '2026-04-10',
        itemStatus: WorkRequestItemStatus.PENDING,
        createdAt: '2026-04-10T10:00:00Z',
        updatedAt: '2026-04-10T10:00:00Z',
      },
    ],
    attachments: [
      {
        id: 'att-001',
        workRequestId: 'st-001',
        fileName: 'evidencia-foto.jpg',
        fileUrl: '/uploads/evidencia-foto.jpg',
        fileType: 'image/jpeg',
        uploadedByUserId: 'user-001',
        uploadedAt: '2026-04-10T10:05:00Z',
      },
    ],
    statusHistory: [
      {
        id: 'hist-001',
        workRequestId: 'st-001',
        fromStatus: WorkRequestStatus.DRAFT,
        toStatus: WorkRequestStatus.DRAFT,
        changedByUserId: 'user-001',
        changedAt: '2026-04-10T10:00:00Z',
      },
    ],
    generalNotes: 'Prioridad máxima por vencimiento próximo.',
    pdfUrl: '/pdfs/ST-2026-001.pdf',
    emailSentTo: 'oficina.tecnica@aero.com',
    otReference: undefined,
    returnedSignedOtUrl: undefined,
    currentOfficeStatus: undefined,
    sentAt: undefined,
    reviewedAt: undefined,
    closedAt: undefined,
  },
  {
    id: 'st-ot-001',
    folio: 'ST-2026-009',
    aircraftId: 'acft-001',
    status: WorkRequestStatus.SIGNED_OT_RECEIVED,
    priority: 'alta',
    createdByUserId: 'user-001',
    assignedToOfficeUserId: 'user-ot-001',
    createdAt: '2026-04-11T09:00:00Z',
    sentAt: '2026-04-11T10:00:00Z',
    otReference: 'OT-2026-011',
    otReceivedAt: '2026-04-12T17:30:00Z',
    returnedSignedOtUrl: '/uploads/ot/OT-2026-011-firmada.pdf',
    updatedAt: '2026-04-12T17:30:00Z',
    items: [
      {
        id: 'item-ot-001',
        workRequestId: 'st-ot-001',
        sourceKind: 'component_inspection',
        sourceId: 'task-component-001',
        ataCode: '72-20-00',
        referenceCode: 'CMP-72-20',
        title: 'Reemplazo de componente critico',
        description: 'Sustitucion de componente por vencimiento de limite.',
        regulatoryBasis: 'AMM 72-20-00',
        requiresComponentTracking: true,
        executionType: 'component_replacement',
        componentDefinitionId: 'comp-def-001',
        priority: 'alta',
        aircraftHoursAtRequest: 2140,
        aircraftCyclesAtRequest: 1290,
        dateAtRequest: '2026-04-11',
        itemStatus: WorkRequestItemStatus.APPROVED,
        createdAt: '2026-04-11T09:00:00Z',
        updatedAt: '2026-04-12T17:30:00Z',
      },
    ],
    attachments: [],
    statusHistory: [
      {
        id: 'hist-ot-001',
        workRequestId: 'st-ot-001',
        fromStatus: WorkRequestStatus.DRAFT,
        toStatus: WorkRequestStatus.SIGNED_OT_RECEIVED,
        changedByUserId: 'user-ot-001',
        changedAt: '2026-04-12T17:30:00Z',
        comment: 'OT firmada recibida',
      },
    ],
  },
];
